
import React, { useState, useRef, useCallback } from 'react';
import { motion, AnimatePresence } from 'motion/react';
// import ReactMarkdown from 'react-markdown'; // Deprecated as per user request
// import remarkGfm from 'remark-gfm';
import {
  DocumentTextIcon,
  ArrowDownTrayIcon,
  ArrowPathIcon,
  XMarkIcon,
  EyeIcon,
  CodeBracketIcon,
  ClipboardDocumentIcon,
  PrinterIcon,
  CheckIcon,
  ChevronDownIcon,
  PencilSquareIcon
} from '@heroicons/react/24/outline';
import { 
  Copy as LucideCopy, 
  ChevronDown as LucideChevronDown,
  Sparkles as LucideSparkles,
  FileText as LucideFileText,
  Download as LucideDownload,
  Share2 as LucideShare2
} from 'lucide-react';

interface ArtifactCanvasProps {
  content: string;
  title: string;
  id?: string;
  type?: 'document' | 'casefile' | 'affidavit' | 'legal_memo' | 'contract';
  onContentChange: (content: string) => void;
  onClose: () => void;
  onRegenerate: () => void;
  isStreaming?: boolean;
  versions?: Array<{ content: string; timestamp: Date; author?: string }>;
  onVersionChange?: (index: number) => void;
}

const GoogleDriveIcon = ({ size = 20 }: { size?: number }) => (
  <img 
    src="/google-drive.png" 
    alt="Google Drive" 
    style={{ width: size, height: size, objectFit: 'contain' }}
  />
);
const ArtifactCanvas: React.FC<ArtifactCanvasProps> = ({
  content,
  title,
  type = 'document',
  onContentChange,
  onClose,
  onRegenerate,
  isStreaming = false,
  versions = [],
  onVersionChange
}) => {
  const [viewMode, setViewMode] = useState<'preview' | 'code'>('preview');
  const [isProfessionalMode, setIsProfessionalMode] = useState(true);
  const [currentVersionIdx, setCurrentVersionIdx] = useState(versions.length > 0 ? versions.length - 1 : 0);
  const [copied, setCopied] = useState(false);
  const [isActionsOpen, setIsActionsOpen] = useState(false);
  const printRef = useRef<HTMLDivElement>(null);
  const actionsRef = useRef<HTMLDivElement>(null);

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      console.error('Failed to copy');
    }
  }, [content]);

  const handleDownloadPDF = useCallback(() => {
    if (!printRef.current) return;
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;
    
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>${title}</title>
          <style>
            @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;700&family=Merriweather:wght@400;700&display=swap');
            body { 
              font-family: 'Merriweather', Georgia, serif; 
              padding: 1in; 
              line-height: 1.6; 
              color: #1a1a1b;
              max-width: 8.5in;
              margin: 0 auto;
              background: white;
            }
            .artifact-html-content { width: 100%; }
            table { border-collapse: collapse; width: 100%; margin: 20px 0; border: 1.5px solid #000; }
            th, td { border: 1px solid #000; padding: 10px; text-align: left; vertical-align: top; }
            th { background: #f0f0f0; font-weight: bold; text-transform: uppercase; font-size: 12px; }
            h1, h2, h3 { font-family: 'Inter', sans-serif; font-weight: 700; color: #000; }
            h1 { text-align: center; border-bottom: 2px solid #000; padding-bottom: 10px; margin-bottom: 40px; }
            .header { text-align: center; margin-bottom: 50px; border-bottom: 1px solid #eee; padding-bottom: 20px; }
            .watermark { position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%) rotate(-45deg); font-size: 80px; color: rgba(0,0,0,0.03); z-index: -1; pointer-events: none; font-weight: 900; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>${title}</h1>
            <small>Generated by Lawlify AI &bull; ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}</small>
          </div>
          ${printRef.current.innerHTML}
          <div class="footer">
            <p>This document was generated by Lawlify AI. It is for informational purposes and does not constitute legal advice.</p>
          </div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => printWindow.print(), 500);
  }, [content, title]);

  const wordCount = content.split(/\s+/).filter(Boolean).length;
  const charCount = content.length;

  // Function to get display name for type
  const getTypeName = () => {
    switch(type) {
      case 'casefile': return 'Casefile';
      case 'affidavit': return 'Affidavit';
      case 'legal_memo': return 'Legal Memo';
      case 'contract': return 'Contract';
      default: return 'Document';
    }
  };

  // Click outside to close actions
  React.useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (actionsRef.current && !actionsRef.current.contains(event.target as Node)) {
        setIsActionsOpen(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  return (
    <motion.div
      initial={{ opacity: 0, x: 50, width: 0 }}
      animate={{ opacity: 1, x: 0, width: '100%' }}
      exit={{ opacity: 0, x: 50, width: 0 }}
      className="h-full bg-white flex flex-col border-l border-gray-100 relative z-10"
    >
      {/* Premium Header Bar */}
      <div className="flex items-center justify-between px-12 py-6 border-b border-gray-100 bg-white/50 backdrop-blur-md sticky top-0 z-[60]">
        <div className="flex items-center gap-4">
          <div className="w-10 h-10 bg-primary/10 rounded-xl flex items-center justify-center">
            <LucideFileText className="w-6 h-6 text-primary" />
          </div>
          <div>
            <h2 className="text-sm font-black text-gray-900 tracking-tight uppercase">{title || 'Untitled Document'}</h2>
            <div className="flex items-center gap-3 mt-1">
              <span className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">{getTypeName()}</span>
              <span className="w-1 h-1 bg-gray-300 rounded-full" />
              <span className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">{wordCount} Words</span>
            </div>
          </div>
        </div>

        <div className="flex items-center gap-2">
          {/* View Toggle */}
          <div className="flex items-center bg-gray-100 p-1 rounded-xl mr-4">
            <button
              onClick={() => setViewMode('preview')}
              className={`flex items-center gap-2 px-4 py-1.5 rounded-lg text-xs font-bold transition-all ${
                viewMode === 'preview' ? 'bg-white text-primary shadow-sm' : 'text-gray-500 hover:text-gray-900'
              }`}
            >
              <EyeIcon className="w-4 h-4" />
              Preview
            </button>
            <button
              onClick={() => setViewMode('code')}
              className={`flex items-center gap-2 px-4 py-1.5 rounded-lg text-xs font-bold transition-all ${
                viewMode === 'code' ? 'bg-white text-primary shadow-sm' : 'text-gray-500 hover:text-gray-900'
              }`}
            >
              <CodeBracketIcon className="w-4 h-4" />
              Code
            </button>
          </div>

          <button
            onClick={handleCopy}
            className="flex items-center gap-2 px-4 py-2 text-gray-600 hover:text-primary hover:bg-primary/5 rounded-xl text-xs font-bold transition-all active:scale-95"
          >
            {copied ? <CheckIcon className="w-4 h-4 text-green-500" /> : <LucideCopy className="w-4 h-4" />}
            {copied ? 'Copied' : 'Copy'}
          </button>

          <button
            onClick={handleDownloadPDF}
            className="flex items-center gap-2 px-4 py-2 bg-black text-white rounded-xl text-xs font-bold hover:bg-gray-800 transition-all active:scale-95 ml-2 shadow-lg shadow-black/10"
          >
            <LucideDownload className="w-4 h-4" />
            Download PDF
          </button>

          <div className="w-[1px] h-8 bg-gray-100 mx-4" />

          <button
            onClick={onClose}
            className="p-2 text-gray-400 hover:text-black hover:bg-gray-100 rounded-full transition-all"
          >
            <XMarkIcon className="w-6 h-6" />
          </button>
        </div>
      </div>

      {/* Content Area */}
      <div className="flex-1 overflow-y-auto no-scrollbar relative flex justify-center bg-white">
        <AnimatePresence mode="wait">
          {viewMode === 'preview' ? (
            <motion.div
              key="preview"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className={`w-full bg-white min-h-full p-16 md:p-32 relative ${isProfessionalMode ? 'font-serif' : 'font-sans'}`}
            >
              <div ref={printRef} className={`prose prose-slate max-w-4xl mx-auto prose-headings:tracking-tight prose-h1:text-2xl prose-h2:text-xl prose-p:text-[17px] prose-p:leading-[1.8] prose-p:text-[#1a1a1b] prose-li:text-[16px] prose-li:leading-[1.8] prose-blockquote:border-l-primary prose-blockquote:bg-red-50/30 ${isProfessionalMode ? 'prose-p:text-justify text-justify' : ''}`}>
                {content ? (
                  <div 
                    dangerouslySetInnerHTML={{ __html: content }} 
                    className="artifact-html-content"
                  />
                ) : (
                  <div className="flex flex-col items-center justify-center h-[50vh] text-center opacity-30">
                    <div className="w-20 h-20 bg-gray-100 rounded-full flex items-center justify-center mb-6 border-4 border-white shadow-inner">
                      <DocumentTextIcon className="w-10 h-10 text-gray-300" />
                    </div>
                    <p className="text-xl font-bold text-gray-400 tracking-tight mb-2">
                      Your artifact will appear here
                    </p>
                    <p className="text-sm text-gray-400 max-w-sm">
                      Ask Lawlify to draft a contract, letter, or legal memo and it will stream directly into this canvas.
                    </p>
                  </div>
                )}

                {isStreaming && (
                  <span className="inline-block w-2 h-5 bg-primary/60 animate-pulse ml-0.5 rounded-sm" />
                )}
              </div>
            </motion.div>
          ) : (
            <motion.div
              key="code"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="w-full bg-white min-h-full relative flex flex-col pt-8"
            >
              <div className="px-12 py-4 bg-gray-50/50 border-y border-gray-100 flex items-center justify-between mx-12 rounded-xl mb-8">
                <span className="text-[11px] text-gray-500 font-mono font-bold uppercase tracking-widest">Pure HTML Source</span>
                <span className="text-[11px] text-gray-400 font-mono">{title || 'artifact'}.html</span>
              </div>
              <textarea
                value={content}
                onChange={(e) => onContentChange(e.target.value)}
                className="flex-1 w-full max-w-6xl mx-auto resize-none border-none outline-none font-mono text-[14px] leading-[1.8] text-gray-800 bg-transparent px-12 py-6 min-h-[70vh]"
                spellCheck={false}
              />
            </motion.div>
          )}
        </AnimatePresence>
      </div>

    </motion.div>
  );
};

const ActionButton = ({ icon, label, onClick }: { icon: React.ReactNode; label: string; onClick?: () => void }) => (
  <button
    onClick={onClick}
    className="w-full flex items-center gap-3 px-3 py-2.5 text-[11px] font-bold text-gray-600 hover:text-black hover:bg-gray-50 rounded-xl transition-all"
  >
    {icon}
    {label}
  </button>
);

export default ArtifactCanvas;
