import React, { useState } from 'react';
import { 
  FileText, 
  Search, 
  Clock, 
  Filter, 
  MoreVertical, 
  Download, 
  Trash2, 
  Eye, 
  ArrowRight,
  Sparkles,
  Info,
  Scale
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { Draft } from '../types';

const MOCK_AI_DRAFTS: Draft[] = [
  { 
    id: '1', 
    title: 'Plaint: Civil Suit No. 24 of 2024', 
    content: 'Statement of claim regarding breach of contract...', 
    type: 'document', 
    lastModified: new Date() 
  },
  { 
    id: '2', 
    title: 'Legal Opinion: Tax Compliance (FinAct 2023)', 
    content: 'Review of potential liabilities under the new regime...', 
    type: 'advice', 
    lastModified: new Date(Date.now() - 86400000) 
  },
  { 
    id: '3', 
    title: 'Notice to Vacate: Commercial Lease', 
    content: 'Formal notice issued on behalf of the landlord...', 
    type: 'document', 
    lastModified: new Date(Date.now() - 172800000) 
  },
];

const DraftsPage: React.FC = () => {
  const [searchQuery, setSearchQuery] = useState('');
  const [filter, setFilter] = useState<'all' | 'document' | 'advice' | 'email'>('all');

  const filteredDrafts = MOCK_AI_DRAFTS.filter(draft => {
    const matchesSearch = draft.title.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesFilter = filter === 'all' || draft.type === filter;
    return matchesSearch && matchesFilter;
  });

  const getTypeIcon = (type: string) => {
    switch (type) {
      case 'document': return <FileText className="w-4 h-4" />;
      case 'advice': return <Scale className="w-4 h-4" />;
      case 'email': return <Eye className="w-4 h-4" />;
      default: return <FileText className="w-4 h-4" />;
    }
  };

  const getStatusColor = (type: string) => {
    switch (type) {
      case 'document': return 'text-blue-500 bg-blue-500/10 border-blue-500/20';
      case 'advice': return 'text-emerald-500 bg-emerald-500/10 border-emerald-500/20';
      case 'email': return 'text-purple-500 bg-purple-500/10 border-purple-500/20';
      default: return 'text-gray-500 bg-gray-500/10 border-gray-500/20';
    }
  };

  return (
    <div className="flex-1 overflow-y-auto bg-white bg-dots p-8">
      <div className="max-w-7xl mx-auto">
        {/* Header Section */}
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 mb-12">
          <div>
            <div className="flex items-center gap-3 mb-2">
              <div className="w-10 h-10 bg-red-50 rounded-xl flex items-center justify-center border border-red-100">
                <FileText className="w-5 h-5 text-red-500" />
              </div>
              <h1 className="text-4xl font-bold tracking-tighter text-black">AI <span className="text-red-500">Drafts</span></h1>
            </div>
            <p className="text-gray-500 text-sm font-medium">Manage and refine documents generated by Lawlify AI</p>
          </div>

          <div className="flex flex-col sm:flex-row gap-4">
            <div className="relative group">
              <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 group-focus-within:text-red-500 transition-colors" />
              <input
                type="text"
                placeholder="Search generated drafts..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full sm:w-64 bg-gray-50 border border-gray-200 rounded-xl py-3 pl-12 pr-4 text-sm font-medium text-black placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-red-500/10 focus:border-red-500/30 transition-all shadow-sm"
              />
            </div>
            <button className="flex items-center justify-center gap-2 px-6 py-3 bg-gray-50 border border-gray-200 rounded-xl text-xs font-bold text-gray-500 hover:text-black hover:bg-gray-100 transition-all">
              <Filter className="w-4 h-4" />
              <span>Filter</span>
            </button>
          </div>
        </div>

        {/* Status Alert */}
        <motion.div 
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-12 p-6 bg-red-50 border border-red-100 rounded-2xl flex items-start gap-4 shadow-sm"
        >
          <div className="w-10 h-10 bg-white rounded-lg flex items-center justify-center shrink-0 shadow-sm border border-red-100">
            <Info className="w-5 h-5 text-red-500" />
          </div>
          <div>
              <h3 className="text-sm font-bold text-red-600 mb-1 font-display">Kenyan Legal Standards Optimization</h3>
              <p className="text-xs text-gray-600 font-medium leading-relaxed max-w-3xl">
                This module is currently being optimized for Kenyan Legal Standards. We are fine-tuning the AI to handle precise statutory citations and court-specific formatting. Please check back soon for the full release.
              </p>
          </div>
        </motion.div>

        {/* Drafts Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredDrafts.map((draft, idx) => (
            <motion.div
              key={draft.id}
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: idx * 0.05 }}
              className="group relative bg-white border border-gray-100 rounded-3xl p-6 hover:shadow-2xl hover:shadow-gray-200/50 hover:border-red-500/20 transition-all cursor-pointer shadow-sm"
            >
              <div className="flex items-start justify-between mb-6">
                <div className={`w-12 h-12 rounded-2xl flex items-center justify-center border shadow-sm ${getStatusColor(draft.type)}`}>
                  {getTypeIcon(draft.type)}
                </div>
                <button className="p-2 text-gray-400 hover:text-black transition-colors">
                  <MoreVertical className="w-5 h-5" />
                </button>
              </div>

              <h4 className="text-lg font-bold text-black mb-2 tracking-tight group-hover:text-red-500 transition-colors line-clamp-1">{draft.title}</h4>
              <p className="text-gray-500 text-xs font-medium leading-relaxed line-clamp-3 mb-6">
                {draft.content}
              </p>

              <div className="flex items-center justify-between pt-6 border-t border-gray-50">
                <div className="flex items-center gap-2 text-gray-400">
                  <Clock className="w-3.5 h-3.5" />
                  <span className="text-[10px] font-bold uppercase tracking-wider">
                    {draft.lastModified.toLocaleDateString('en-KE', { day: 'numeric', month: 'short' })}
                  </span>
                </div>
                <div className="flex items-center gap-1.5 px-3 py-1.5 bg-red-50 text-red-500 text-[10px] font-black rounded-full uppercase tracking-widest border border-red-100 opacity-0 group-hover:opacity-100 transition-all">
                  <span>Open Draft</span>
                  <ArrowRight className="w-3 h-3" />
                </div>
              </div>

              {/* Subtle hover indicator */}
              <div className="absolute top-4 right-4 w-2 h-2 rounded-full bg-red-500 opacity-0 group-hover:opacity-100 transition-opacity" />
            </motion.div>
          ))}
          
          {/* Add New Placeholder - Spans across the page */}
          <div className="col-span-full bg-gray-50/50 border-2 border-gray-100 border-dashed rounded-3xl p-10 flex flex-col md:flex-row items-center justify-between gap-6 group hover:border-red-500/30 hover:bg-red-50/30 transition-all cursor-pointer shadow-sm">
            <div className="flex items-center gap-6">
              <div className="w-16 h-16 bg-white rounded-2xl flex items-center justify-center text-gray-400 group-hover:text-red-500 shadow-sm border border-gray-100 transition-all shrink-0">
                <Sparkles className="w-8 h-8" />
              </div>
              <div className="text-center md:text-left">
                <h5 className="text-xl font-bold text-gray-700 group-hover:text-black transition-colors">Start New AI Draft</h5>
                <p className="text-xs text-gray-500 mt-1 font-medium italic">Use AI to generate professional legal documents in seconds.</p>
              </div>
            </div>
            <button className="px-8 py-4 bg-red-500 text-white rounded-2xl text-xs font-black uppercase tracking-widest shadow-lg shadow-red-500/20 hover:bg-red-600 hover:scale-105 active:scale-95 transition-all">
              Initialize AI Composer
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default DraftsPage;
