import React, { useState, useEffect } from 'react';
import { 
  FileText, 
  Search, 
  Clock, 
  Filter, 
  MoreVertical, 
  Download, 
  Trash2, 
  Eye, 
  ArrowRight,
  Sparkles,
  Info,
  Scale,
  Loader2,
  CheckCircle2
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import { apiClient } from '../lib/apiClient';

const DraftsPage: React.FC = () => {
  const navigate = useNavigate();
  const [drafts, setDrafts] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');
  const [filter, setFilter] = useState<'all' | 'document' | 'advice' | 'email'>('all');
  const [selectedDrafts, setSelectedDrafts] = useState<Set<string>>(new Set());

  useEffect(() => {
    const fetchDrafts = async () => {
      try {
        const res = await apiClient.get('/api/drafts');
        if (res.ok) {
           const data = await res.json();
           setDrafts(data);
        }
      } catch (e) {
        console.error("Failed to fetch drafts", e);
      } finally {
        setIsLoading(false);
      }
    };
    fetchDrafts();
  }, []);

  const filteredDrafts = drafts.filter(draft => {
    const matchesSearch = draft.title.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesFilter = filter === 'all' || draft.type === filter;
    return matchesSearch && matchesFilter;
  });

  const getTypeIcon = (type: string) => {
    switch (type) {
      case 'document': return <FileText className="w-4 h-4" />;
      case 'advice': return <Scale className="w-4 h-4" />;
      case 'email': return <Eye className="w-4 h-4" />;
      default: return <FileText className="w-4 h-4" />;
    }
  };

  const getStatusColor = (type: string) => {
    switch (type) {
      case 'document': return 'text-blue-500 bg-blue-500/10 border-blue-500/20';
      case 'advice': return 'text-emerald-500 bg-emerald-500/10 border-emerald-500/20';
      case 'email': return 'text-purple-500 bg-purple-500/10 border-purple-500/20';
      default: return 'text-gray-500 bg-gray-500/10 border-gray-500/20';
    }
  };

  return (
    <div className="flex-1 overflow-y-auto bg-white bg-dots p-8">
      <div className="max-w-7xl mx-auto">
        {/* Header Section */}
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 mb-12">
          <div>
            <div className="flex items-center gap-3 mb-2">
              <div className="w-10 h-10 bg-red-50 rounded-xl flex items-center justify-center border border-red-100">
                <FileText className="w-5 h-5 text-red-500" />
              </div>
              <h1 className="text-4xl font-bold tracking-tighter text-black">AI <span className="text-red-500">Drafts</span></h1>
            </div>
            <p className="text-gray-500 text-sm font-medium">Manage and refine documents generated by Lawlify AI</p>
          </div>

          <div className="flex flex-col sm:flex-row gap-4">
            <div className="relative group">
              <Search className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 group-focus-within:text-red-500 transition-colors" />
              <input
                type="text"
                placeholder="Search generated drafts..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full sm:w-64 bg-gray-50 border border-gray-200 rounded-xl py-3 pl-12 pr-4 text-sm font-medium text-black placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-red-500/10 focus:border-red-500/30 transition-all shadow-sm"
              />
            </div>
            <button className="flex items-center justify-center gap-2 px-6 py-3 bg-gray-50 border border-gray-200 rounded-xl text-xs font-bold text-gray-500 hover:text-black hover:bg-gray-100 transition-all">
              <Filter className="w-4 h-4" />
              <span>Filter</span>
            </button>
          </div>
        </div>

        {/* Bulk Actions Toolbar */}
        <AnimatePresence>
          {selectedDrafts.size > 0 && (
            <motion.div 
              initial={{ opacity: 0, y: -10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className="mb-8 flex items-center justify-between p-4 bg-slate-900 rounded-[20px] shadow-sm shadow-slate-900/10"
            >
               <div className="flex items-center gap-4 text-white">
                  <button 
                    onClick={() => {
                      if (selectedDrafts.size === filteredDrafts.length) setSelectedDrafts(new Set());
                      else setSelectedDrafts(new Set(filteredDrafts.map(d => d.id)));
                    }} 
                    className="flex items-center gap-2 text-sm font-bold text-slate-300 hover:text-white transition-colors pl-2"
                  >
                     <div className={`w-5 h-5 rounded-md border flex items-center justify-center transition-colors ${selectedDrafts.size === filteredDrafts.length ? 'bg-red-500 border-red-500 text-white' : 'border-slate-500 bg-transparent'}`}>
                        {selectedDrafts.size === filteredDrafts.length && <CheckCircle2 className="w-3.5 h-3.5" />}
                     </div>
                     <span>{selectedDrafts.size} Selected</span>
                  </button>
               </div>
               <div className="flex items-center gap-3">
                  <button className="px-4 py-2 bg-slate-800 text-slate-300 rounded-xl text-xs font-black uppercase tracking-widest hover:bg-slate-700 hover:text-white transition-all flex items-center gap-2 relative z-10 transition-transform active:scale-95">
                     <Download className="w-4 h-4" /> Export
                  </button>
                  <button className="px-4 py-2 bg-red-500 text-white rounded-xl text-xs font-black uppercase tracking-widest shadow-lg shadow-red-500/20 hover:bg-red-600 transition-all flex items-center gap-2 relative z-10 transition-transform active:scale-95">
                     <Trash2 className="w-4 h-4" /> Delete
                  </button>
               </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Drafts Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredDrafts.map((draft, idx) => (
            <motion.div
              key={draft.id}
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              transition={{ delay: idx * 0.05 }}
              className={`group relative bg-white border rounded-[15px] p-6 hover:shadow-2xl hover:shadow-gray-200/50 transition-all cursor-pointer shadow-sm ${selectedDrafts.has(draft.id) ? 'border-red-500 ring-2 ring-red-500/20' : 'border-gray-100 hover:border-red-500/20'}`}
              onClick={() => {
                 const newSet = new Set(selectedDrafts);
                 if (newSet.has(draft.id)) newSet.delete(draft.id);
                 else newSet.add(draft.id);
                 setSelectedDrafts(newSet);
              }}
            >
              <button 
                className={`absolute top-4 right-4 z-20 w-6 h-6 rounded-full border-2 flex items-center justify-center transition-all ${
                  selectedDrafts.has(draft.id) 
                  ? 'bg-red-500 border-red-500 text-white opacity-100 scale-100' 
                  : 'bg-white border-gray-300 text-transparent opacity-0 scale-90 group-hover:opacity-100 group-hover:scale-100 hover:border-gray-400'
                }`}
              >
                <CheckCircle2 className="w-4 h-4" />
              </button>
              <div className="flex items-start justify-between mb-6 relative z-10 pointer-events-none">
                <div className={`w-12 h-12 rounded-2xl flex items-center justify-center border shadow-sm ${getStatusColor(draft.type)}`}>
                  {getTypeIcon(draft.type)}
                </div>
                <button className="p-2 text-gray-400 hover:text-black transition-colors">
                  <MoreVertical className="w-5 h-5" />
                </button>
              </div>

              <h4 className="text-lg font-bold text-black mb-2 tracking-tight group-hover:text-red-500 transition-colors line-clamp-1">{draft.title}</h4>
              <p className="text-gray-500 text-xs font-medium leading-relaxed line-clamp-3 mb-6">
                {draft.content}
              </p>

              <div className="flex items-center justify-between pt-6 border-t border-gray-50">
                <div className="flex items-center gap-2 text-gray-400">
                  <Clock className="w-3.5 h-3.5" />
                  <span className="text-[10px] font-bold uppercase tracking-wider">
                    {new Date(draft.updated_at || draft.lastModified || Date.now()).toLocaleDateString('en-KE', { day: 'numeric', month: 'short' })}
                  </span>
                </div>
                <div className="flex items-center gap-1.5 px-3 py-1.5 bg-red-50 text-red-500 text-[10px] font-black rounded-full uppercase tracking-widest border border-red-100 opacity-0 group-hover:opacity-100 transition-all">
                  <span>Open Draft</span>
                  <ArrowRight className="w-3 h-3" />
                </div>
              </div>

              {/* Subtle hover indicator */}
              <div className="absolute top-4 right-4 w-2 h-2 rounded-full bg-red-500 opacity-0 group-hover:opacity-100 transition-opacity" />
            </motion.div>
          ))}
          
          {/* Add New Placeholder - Spans across the page */}
          <div 
            onClick={() => navigate('/app/specialists', { state: { editSpecialistId: 'doc-prep' } })}
            className="col-span-full relative overflow-hidden bg-red-600 rounded-[15px] p-10 flex flex-col md:flex-row items-center justify-between gap-8 group hover:shadow-2xl hover:shadow-red-500/40 hover:-translate-y-1 transition-all cursor-pointer outline-none shadow-lg"
          >
            {/* Background design elements */}
            <div className="absolute top-0 right-0 w-96 h-96 bg-gradient-to-br from-red-500 to-red-600 rounded-full blur-3xl opacity-50 -translate-y-1/2 translate-x-1/2" />
            
            <div className="flex items-center gap-6 relative z-10 w-full md:w-auto">
              <div className="w-16 h-16 bg-white/10 backdrop-blur-md rounded-2xl flex items-center justify-center text-white border border-white/20 shadow-inner shrink-0 group-hover:scale-110 group-hover:rotate-3 transition-transform duration-500">
                <Sparkles className="w-8 h-8" />
              </div>
              <div className="text-center md:text-left flex-1">
                <h5 className="text-2xl font-black text-white tracking-tight">Start New AI Draft</h5>
                <p className="text-sm text-red-100 mt-1.5 font-medium leading-relaxed">Use AI to generate professional legal documents in seconds.</p>
              </div>
            </div>
            
            <button 
              onClick={(e) => {
                e.stopPropagation();
                navigate('/app/specialists', { state: { editSpecialistId: 'doc-prep' } });
              }}
              className="w-full md:w-auto px-8 py-4 bg-black text-white rounded-2xl text-[11px] font-black uppercase tracking-widest shadow-xl shadow-black/20 hover:bg-gray-900 flex items-center justify-center gap-3 shrink-0 hover:scale-105 active:scale-95 transition-all relative z-10 border border-black/50"
            >
              Initialize AI Composer
              <ArrowRight className="w-4 h-4 opacity-70 group-hover:translate-x-1 transition-transform" />
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default DraftsPage;
